package execution

import (
	"errors"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"unicode/utf8"
)

type workspace struct {
	path string
}

var (
	ErrTooManyArtifacts       = errors.New("too many artifacts")
	ErrArtifactTooLarge       = errors.New("artifact too large")
	ErrTotalArtifactsTooLarge = errors.New("total artifact size too large")
)

func createWorkspace(files []InputFile) (*workspace, error) {
	dir, err := os.MkdirTemp("", "agent-executor-*")

	if err != nil {
		return nil, err
	}

	ws := &workspace{path: dir}

	if err := ws.writeFiles(files); err != nil {
		_ = ws.cleanup()
		return nil, err
	}

	return ws, nil
}

func (w *workspace) writeFiles(files []InputFile) error {
	for _, file := range files {
		targetPath := filepath.Join(w.path, filepath.FromSlash(file.Path))

		if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
			return err
		}

		if err := os.WriteFile(targetPath, []byte(file.Content), 0644); err != nil {
			return err
		}
	}

	return nil
}

func (w *workspace) cleanup() error {
	return os.RemoveAll(w.path)
}

func (w *workspace) collectArtifacts(inputFiles []InputFile, cfg DockerConfig) ([]Artifact, error) {
	// Track the original input files so they are not returned as generated artifacts.
	inputPaths := make(map[string]struct{}, len(inputFiles))
	for _, file := range inputFiles {
		inputPaths[file.Path] = struct{}{}
	}

	var artifacts []Artifact
	var totalSize int64

	// Walk the workspace after execution and collect files created by the user code.
	err := filepath.WalkDir(w.path, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Directories are part of the workspace structure, but they are not artifacts.
		if d.IsDir() {
			return nil
		}

		// Convert the host filesystem path back into a workspace-relative path.
		// This avoids exposing temporary host paths in the API response.
		relativePath, err := filepath.Rel(w.path, path)
		if err != nil {
			return err
		}

		// Normalize artifact paths to slash-based API paths, even on Windows.
		artifactPath := filepath.ToSlash(relativePath)

		// Skip files that were provided as inputs. Artifacts should represent
		// files generated by the executed code, not files the caller submitted.
		if _, isInputFile := inputPaths[artifactPath]; isInputFile {
			return nil
		}

		info, err := d.Info()
		if err != nil {
			return err
		}

		size := info.Size()

		// Enforce artifact limits before reading any file content into memory.
		if len(artifacts) >= cfg.MaxArtifactCount {
			return fmt.Errorf("%w: max %d", ErrTooManyArtifacts, cfg.MaxArtifactCount)
		}

		if size > cfg.MaxArtifactSizeBytes {
			return fmt.Errorf("%w: %s is %d bytes, max %d", ErrArtifactTooLarge, artifactPath, size, cfg.MaxArtifactSizeBytes)
		}

		totalSize += size
		if totalSize > cfg.MaxTotalArtifactSizeBytes {
			return fmt.Errorf("%w: got %d bytes, max %d", ErrTotalArtifactsTooLarge, totalSize, cfg.MaxTotalArtifactSizeBytes)
		}

		artifact := Artifact{
			Path: artifactPath,
			Size: size,
		}

		// Inline only small UTF-8 text artifacts. Larger files are returned as
		// metadata-only artifacts for now, and binary inline/base64 support can
		// be added later.
		if size <= cfg.MaxInlineArtifactBytes {
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}

			if utf8.Valid(data) {
				artifact.Content = string(data)
				artifact.Encoding = "utf-8"
				artifact.ContentType = http.DetectContentType(data)
			}
		}

		artifacts = append(artifacts, artifact)
		return nil

	})

	if err != nil {
		return nil, err
	}

	return artifacts, nil
}
